name: build
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Configure JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/dists
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.properties', 'gradle/**') }}
          restore-keys: -${{ runner.os }}-gradle-
      - name: Build library artifacts
        run: ./gradlew -p library assemble
      - name: Run library test suite
        run: ./gradlew -p library check
      - name: Build tracing artifacts
          run: ./gradlew -p tracing assemble
      - name: Run tracing test suite
        run: ./gradlew -p tracing check
      - name: Code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./library/build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true
